### PR TITLE
Add pretty printing for particle directions, species, and spin/pol

### PR DESCRIPTION
**Pull request by AntonReinhard**
Just what the title says. I want to add some pretty printing in QEDprocesses as well, and these are helpful for that. I also added jldoctests.

### CODE REVIEW

**Comment by AntonReinhard** [comment]
To stay in accordance with https://docs.julialang.org/en/v1/manual/types/#man-custom-pretty-printing , I've now only overloaded the 3-argument show function, i.e. the one used when `display()` is called.

```julia
julia> Electron()
electron

julia> [Electron(), Positron(), Photon()]
3-element Vector{AbstractParticleType}:
 electron
 positron
 photon

julia> print(Electron())
Electron()
```

**Review by szabo137 — APPROVED** [review]
Thanks for this, looks good to me 👌

**Comment by AntonReinhard** [comment]
One question before we merge: I added QEDbase to the docs/Project.toml by simply building the docs (to check the jldoctests). Should it be in there? I'm wondering if there's a reason it wasn't before

**Comment by szabo137** [comment]
> One question before we merge: I added QEDbase to the docs/Project.toml by simply building the docs (to check the jldoctests). Should it be in there? I'm wondering if there's a reason it wasn't before

I think adding QEDbase to the Project.toml of the docs is correct. Currently, we use the workaround `docs/make.jl:4-7`, which should be removed at some point.

**Pull request merged**
