### PR TITLE
ci: add unit tests

### PR DESCRIPTION
**Pull request by SimeonEhrig**
see [documentation](https://github.com/QEDjl-project/QED.jl/blob/dev/docs/src/ci.md#unit-tests-for-ci-users)

### CODE REVIEW

**Review by szabo137 — COMMENTED** [review]
Is it really necessary to replace the whole `.gitlab-ci.yml`, maybe you could leave at least the linter stage in place.

**Comment by SimeonEhrig** [comment]
Does the formatter job only check's if it correct formatted? I'm a little bit confused, because the execution is restricted to pull request to the branch dev and main.

**Comment by szabo137** [comment]
Indeed, the formatter checks, if the code is correctly formatted, i.e. Blue style. The idea behind the trigger rules was, that only well-formatted PR should go through so that eventually the codebase stays in one format.

**Comment by SimeonEhrig** [comment]
Okay. The rules will not work anymore, because of the mirror feature, it does not open a MR. It simply creates new branch in the upstream repo and push a commit. But I think the rules are not required.

**Comment by SimeonEhrig** [comment]
@szabo137 I added the formatter. It works in general. But the can-fail status is not display in GitHub. Instead it shows all fine.
Test-Commit: b156f0b
CI Pipeline: https://gitlab.com/hzdr/qedjl-project/QEDbase-jl/-/pipelines/975875974

I'm not sure, if we want to remove the `allow_failure: true` flag.

**Comment by szabo137** [comment]
Oh, that is a pity. Maybe it would be more convenient to move the linter stage to the latest position, after all other tests are passed, and don't allow the linter to fail. Then the whole pipeline fails on the linter an the report icon in GitHub becomes red, isn't it?

**Comment by szabo137** [comment]
I do agree with this statement. Then I suggest leaving the linter stage at the first position, but we need to remark the "exclamation mark job" in a review guide in the docs of `QED.jl`.

**Comment by SimeonEhrig** [comment]
Do you mean, also keep the `allow_failure: true`?
We can also run the formatter and the test in the same stage. Then the test are executed but you cannot accidentally merge, if the code is not correct formatted.

**Comment by SimeonEhrig** [comment]
During developing the PR, I would agree but not if you want to merge it. In this case the code is not correct formatted when it be merged, the next person which modifies the file has a problem. Ether he also format parts, which he does not modified and this appears in the PR or he needs some extra work to format only the part, which he modified. I had the problem with the cling project in the past.

But I don't see technical solution, which prevent use to merge a PR, if the formatter job failed. We have to check the pipeline manually each time, if the job passed, before we hit the merge button.

**Comment by szabo137** [comment]
I am not happy with this solution. Maybe it would be better, if we use Workflows from GitHub for formatting, instead of the GitLab route. 

Nevertheless, to proceed with this PR, I suggest to leave the "you must check the pipeline by yourself" version, but opening an critical issue on this problem in this Repo (and maybe in the repo of the Bot itself) .

**Review by szabo137 — DISMISSED** [review]
As argued in the comments, this this is not the best solution for the linting stage. However, there are no concerns with the unit-test stages, so I am happy to merge this!

**Comment by szabo137** [comment]
Ok, one last thing: the latest commit b156f0b1 did not pass the linter stage 🤷‍♂️

**Comment by SimeonEhrig** [comment]
I removed commit b156f0b1d465859c01adbf6843539e1714fc00e9 because it was only for demonstration. So the current state is, that the formatter runs before unit tests and can fail. If it is fine, merge it.

**Review by szabo137 — APPROVED** [review]
Excellent! Merged!

**Pull request merged**
