### PR TITLE
[DO NOT MERGE] test PR to fix CI problems of PR #134

### PR DESCRIPTION
**Pull request by SimeonEhrig**

### CODE REVIEW

**Review by AntonReinhard — COMMENTED** [review]
You should also adjust the QED.jl link in `.github/workflows/BuildDeployDoc.yml` for testing

**Comment by AntonReinhard** [comment]
The error message looks like it might be running the tests with the dev version of QEDbase instead of the PR version? Though I'm not sure how that's happening.

The tests succeed locally for me, so I think it is an issue of the CI.

**Comment by SimeonEhrig** [comment]
> The tests succeed locally for me, so I think it is an issue of the CI.

I can reproduce it in a container. And also if I checkout the dev, the error is gone.

**Comment by SimeonEhrig** [comment]
> > It's a bug in the implementation. I can solve with the following patch:
> > ```diff
> > diff --git a/test/test_implementation/test_phase_space_layout.jl b/test/test_implementation/test_phase_space_layout.jl
> > index 78010f1..c7c5b14 100644
> > --- a/test/test_implementation/test_phase_space_layout.jl
> > +++ b/test/test_implementation/test_phase_space_layout.jl
> > @@ -2,7 +2,7 @@
> >  ### Trivial phase-space layouts
> >  
> >  # maps all components onto four momenta
> > -struct TrivialInPSL <: AbstractInPhaseSpaceLayout end
> > +struct TrivialInPSL <: QEDbase.AbstractInPhaseSpaceLayout end
> >  
> >  @inline QEDbase.phase_space_dimension(
> >      proc::AbstractProcessDefinition, ::AbstractModelDefinition, ::TrivialInPSL
> > @@ -15,7 +15,7 @@ struct TrivialInPSL <: AbstractInPhaseSpaceLayout end
> >  end
> >  
> >  # maps componets of N-1 particles onto four-momenta and uses energy-momentum conservation
> > -struct TrivialOutPSL <: AbstractOutPhaseSpaceLayout{TrivialInPSL}
> > +struct TrivialOutPSL <: QEDbase.AbstractOutPhaseSpaceLayout{TrivialInPSL}
> >      in_psl::TrivialInPSL
> >  end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't know, why `AbstractInPhaseSpaceLayout` and `AbstractOutPhaseSpaceLayout` needs the `QEDbase`. They are exported, therefore it should be not necessary.
> 
> The problem is, that `AbstractInPhaseSpaceLayout` and alike are currently also defined in QEDcore (because there, it was a patch). Therefore, I would like to leave #134 open and add a fix to QEDcore (just removing `patch_QEDbase.jl` and respective tests). This should fix the bug above.
> 
> Btw: in the future, we will not allow adding `patch_*.jl` files to `dev` to avoid these kinds of bugs.

But this means, that the CI should work.

**Comment by SimeonEhrig** [comment]
@szabo137 The patch looks good :-)

**Pull request closed without merging**
