### PR TITLE
add formatter job to GitHub Actions

### PR DESCRIPTION
**Pull request by SimeonEhrig**

### CODE REVIEW

**Review by szabo137 — DISMISSED** [review]
Wait, why is the formatting job not triggered on this PR?

**Comment by szabo137** [comment]
I guess you could add `on: workflow_dispatch` to the workflow definition, so we may trigger the job manually (see [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) for details).

**Comment by SimeonEhrig** [comment]
@szabo137 Maybe I found the reason, why the Github Workflow is not triggered: https://stackoverflow.com/a/77161850/22035743
Maybe the workflow will be triggered the first time, if we merge in dev and open a new repository. Therefore, the PR only adds the GitHub formatter job and keeps the GitLab CI formatter job for the moment.

If everything is working, I remove the GitLab CI formatter in a following up PR:

**Comment by szabo137** [comment]
Since this PR is not breaking any functionality of the package, I will follow @SimeonEhrig suggestion to merge it into `dev`, and see if the action is triggered for formatting.

**Review by szabo137 — APPROVED** [review]

**Pull request merged**
