### PR TITLE
Test GPU Unit tests

### PR DESCRIPTION
**Pull request by SimeonEhrig**

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
@AntonReinhard Did you test the AMDGPU code locally? I can reproduce the error locally on HAL and fwk394 bare metal and in a container on HAL. Looks like the code is wrong.

**Comment by AntonReinhard** [comment]
> @AntonReinhard Did you test the AMDGPU code locally? I can reproduce the error locally on HAL and fwk394 bare metal and in a container on HAL. Looks like the code is wrong.

No, I could only test with oneAPI so far.

**Comment by AntonReinhard** [comment]
I have opened https://github.com/QEDjl-project/QEDcore.jl/pull/90 to fix this issue.

**Comment by AntonReinhard** [comment]
As the testing was successful, and the GPU test functionality has been merged, this can be closed.

**Pull request closed without merging**
