### PR TITLE
Release 0.3.0 to main

### PR DESCRIPTION
**Pull request by AntonReinhard**
Release the new features to main in a new release process.

This is a release to main, **do not squash or rebase**

### CODE REVIEW

**Comment by AntonReinhard** [comment]
The doc building job fails because it's not setting the dev dependencies of the QEDproject packages, see the if condition:
```
      - name: set dependencies to dev branch version
        if: (github.event_name == 'push' && github.ref_name != 'main') || (github.event_name == 'pull_request' && github.base_ref != 'main')
```
I don't think this is intentional as we should always build the docs against the dev versions or they will fail in cases like this one, where breaking changes are introduced that cannot be released in the downstream packages yet.
@SimeonEhrig should I just delete the `github.ref_name != 'main'` conditions?

**Review by szabo137 — COMMENTED** [review]
There are several broken integration tests. It seems to be a compatibility problem. I suggest to update the packages depending on `QEDbase.jl` first, by replacing the pinned `[compat]` entry with a lower bound, e.g. "^0.2". After that, the integration tests in this PR should pass, and we can proceed with the release process.

**Comment by AntonReinhard** [comment]
> There are several broken integration tests. It seems to be a compatibility problem. I suggest to update the packages depending on `QEDbase.jl` first, by replacing the pinned `[compat]` entry with a lower bound, e.g. "^0.2". After that, the integration tests in this PR should pass, and we can proceed with the release process.

`^` is already the default specifier according to https://pkgdocs.julialang.org/v1/compatibility/. In any case, the point of the `compat` is to specify which versions are compatible, and allowing "any version higher than x" goes against that, when there can be breaking changes in the future that would automatically be included.

The problem isn't really with the compat entries, they are as they should be, the problem is that we want to "override" the compat entries for the testing. I think the simplest solution might be to modify the `Project.toml` in the package that the integration test is being created for, by deleting the currently tested package's compat entry entirely, so the resolve can't refuse installing it.

**Comment by szabo137** [comment]
> `^` is already the default specifier according to https://pkgdocs.julialang.org/v1/compatibility/. In any case, the point of the `compat` is to specify which versions are compatible, and allowing "any version higher than x" goes against that, when there can be breaking changes in the future that would automatically be included.

I see, you are right. 

> The problem isn't really with the compat entries, they are as they should be, the problem is that we want to "override" the compat entries for the testing. I think the simplest solution might be to modify the Project.toml in the package that the integration test is being created for, by deleting the currently tested package's compat entry entirely, so the resolve can't refuse installing it.

I understand the problem, and I think your suggested solution will work. However, I don't know if it is a good idea to directly change the `Project.toml`, even just for testing. Maybe this would be a good question for discourse 🤔

**Comment by SimeonEhrig** [comment]
> @SimeonEhrig should I just delete the github.ref_name != 'main' conditions?

"The biggest problem of the software development - User!". You constantly breaks my assumptions about the CI. I didn't thought about the possibility, that the documentation could have different dependencies compare to the actual software. Therefore the check forces the same requirement, that the main branch version needs to work with released packages.

But I see the problem. If we force this also for the documentation the QED dependency graph becomes an unmanageable thing, where everything is more or less depend on everything. Therefore I think we can relax the requirements for the documentation. But this also means, our documentation documents feature in the release which are maybe not working yet because a dependent QED project was not released in the required version yet.

@szabo137 What do you think?

**Comment by AntonReinhard** [comment]
There are two separate problems here, one is the documentation build, the other are the integration tests.

### For the docs building:
> "The biggest problem of the software development - User!". You constantly breaks my assumptions about the CI. I didn't thought about the possibility, that the documentation could have different dependencies compare to the actual software. Therefore the check forces the same requirement, that the main branch version needs to work with released packages.

I think the problem is that the docs can have dependencies to packages that are otherwise downstream of the package itself, and therefore needs to be considered similar to the integration tests instead of the unit tests. This does mean, as you say, that there might be docs for a time that aren't reproducible with only released packages, at least until all required downstream packages are released again.
In any case, we now always build the integration tests with dev dependencies and have the release version integration tests only as information for the developer, so always building the docs with dev dependencies too is just streamlining it in my opinion. So simply deleting the `github.ref_name != 'main'` check I mentioned should be an easy fix here that also makes sense.

### Now for the integration tests
I think this is the bigger problem because as I said, we somehow need to force the downstream packages to accept the specific version of the package that we give it, regardless of what the compat tells it to use. The ideal scenario would be if the Julia's package manager allowed some kind of flag to override the compat entry, but from a quick google I can't find anything like this. Maybe it would be possible to ~~steal~~ borrow some code from Julia's CompatHelper to find and change the compat entry manually when generating the integration tests.

**Comment by SimeonEhrig** [comment]
> There are two separate problems here, one is the documentation build, the other are the integration tests.
> ### For the docs building:
> 
> > "The biggest problem of the software development - User!". You constantly breaks my assumptions about the CI. I didn't thought about the possibility, that the documentation could have different dependencies compare to the actual software. Therefore the check forces the same requirement, that the main branch version needs to work with released packages.
> 
> I think the problem is that the docs can have dependencies to packages that are otherwise downstream of the package itself, and therefore needs to be considered similar to the integration tests instead of the unit tests. This does mean, as you say, that there might be docs for a time that aren't reproducible with only released packages, at least until all required downstream packages are released again. In any case, we now always build the integration tests with dev dependencies and have the release version integration tests only as information for the developer, so always building the docs with dev dependencies too is just streamlining it in my opinion. So simply deleting the `github.ref_name != 'main'` check I mentioned should be an easy fix here that also makes sense.
> ### Now for the integration tests
> 
> I think this is the bigger problem because as I said, we somehow need to force the downstream packages to accept the specific version of the package that we give it, regardless of what the compat tells it to use. The ideal scenario would be if the Julia's package manager allowed some kind of flag to override the compat entry, but from a quick google I can't find anything like this. Maybe it would be possible to ~steal~ borrow some code from Julia's CompatHelper to find and change the compat entry manually when generating the integration tests.

Well, the integration tests clones the source code of the project to test. The `Project.toml` is just a toml file. Therefore there is nor reason why we cannot modify the file before we instantiate the project.

**Comment by AntonReinhard** [comment]
It looks like we have the same `compat` problem in the documentation too...

**Comment by SimeonEhrig** [comment]
> It looks like we have the same `compat` problem in the documentation too...

I think this is something what we should discuss tomorrow. I was also thinking if the correct solution is to modify the compat entries of the packages on the dev branch version.

**Comment by AntonReinhard** [comment]
I will have to update the Changelog again, other than that this should (finally) be ready to merge

**Comment by SimeonEhrig** [comment]
@AntonReinhard The CI passed :partying_face:

**Comment by szabo137** [comment]
@SimeonEhrig @AntonReinhard many thanks for you effort making this running (again) 🥳

**Review by szabo137 — APPROVED** [review]
LGFM ✌️

**Pull request merged**
